export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_DETAIL = "FETCH_DETAIL";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING"

//cart
export const ADD_CART = "ADD_CART";
export const DELETE_CART = "DELETE_CART";
export const NUMBER_QUANTITY = "NUMBER_QUANTITY";
export const BUY_PRODUCT = "BUY_PRODUCT";
